/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Image;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import bukawarung.koneksiDB;



/**
 *
 * @author USER
 */
public class Login extends javax.swing.JFrame {
koneksiDB getcnn = new koneksiDB();
Connection _cnn;
String vnama_user,vpass;
String sqlselect;
private static String lev_user="";
private static String id_user="";
public static String xiduser;

    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
       
        
    }
 private void aksilogin(){
        id_user = txtuser.getText().replaceAll("'", "");
        vpass = txtpass.getText().replaceAll("'", "");
        lev_user = cmbLevUser.getSelectedItem().toString();
        try{
            _cnn = null;
            _cnn = getcnn.getConnection();
           sqlselect = "select * from tb_user where id_user = '"+id_user+"' "
                   +" and password = '"+vpass+"' and level_user = '"+lev_user+"' ";
           Statement stat = _cnn.createStatement();
           ResultSet res = stat.executeQuery(sqlselect);
           if(res.first()){
               xiduser = id_user;
               new menu_utama(lev_user).show();
               this.dispose();
           
           }else{
               JOptionPane.showMessageDialog(this,"Ada Kesalahan dalam ","Informasi", JOptionPane.INFORMATION_MESSAGE);
           }
           
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this,"Eror Method Aksi Login() :"+ex);
        }
        
    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnllog = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtpass = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        cmbLevUser = new javax.swing.JComboBox<>();
        jPanel26 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtlihat = new javax.swing.JCheckBox();
        jLabel41 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnllog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnllog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(0, 138, 0));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-shop-96.png"))); // NOI18N

        jLabel35.setBackground(new java.awt.Color(0, 138, 0));
        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("BukaWarung");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel35))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel32)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addGap(193, 193, 193))
        );

        pnllog.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 480));

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel36.setText("ID. User");
        jPanel25.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel37.setText("Password");
        jPanel25.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        txtuser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtuser.setBorder(null);
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        jPanel25.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 208, 30));
        jPanel25.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 208, 10));

        txtpass.setBorder(null);
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        jPanel25.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 208, 29));
        jPanel25.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 208, 10));

        cmbLevUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Level User --", "Pemilik Toko", "Kasir", "Petugas Gudang" }));
        cmbLevUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLevUserActionPerformed(evt);
            }
        });
        jPanel25.add(cmbLevUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 132, 29));

        jPanel26.setBackground(new java.awt.Color(0, 138, 0));
        jPanel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel26MouseClicked(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Login");

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel38)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel38)
                .addContainerGap())
        );

        jPanel25.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-subtract-32.png"))); // NOI18N
        jPanel25.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 5, -1, 20));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-delete-32.png"))); // NOI18N
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
        });
        jPanel25.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 5, -1, 20));

        txtlihat.setBackground(new java.awt.Color(255, 255, 255));
        txtlihat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-eye-24.png"))); // NOI18N
        txtlihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlihatActionPerformed(evt);
            }
        });
        jPanel25.add(txtlihat, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        jLabel41.setBackground(new java.awt.Color(0, 138, 0));
        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 138, 0));
        jLabel41.setText("BukaWarung");
        jPanel25.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        pnllog.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 420, 480));

        getContentPane().add(pnllog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 480));

        setSize(new java.awt.Dimension(639, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void jPanel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel26MouseClicked
        if(txtuser.getText().equals("")|| txtpass.getText().equals("")|| cmbLevUser.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(this,"silahkan lengkapi data !","informasi",
                    JOptionPane.INFORMATION_MESSAGE);
        
        }else{
            aksilogin();
             
            
        }
        
    }//GEN-LAST:event_jPanel26MouseClicked

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel40MouseClicked

    private void cmbLevUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLevUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLevUserActionPerformed

    private void txtlihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlihatActionPerformed
    if (txtlihat.isSelected()) {
      txtpass.setEchoChar((char)0);
      
   } else {
      txtpass.setEchoChar('\u25cf');
     
   }
    }//GEN-LAST:event_txtlihatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbLevUser;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pnllog;
    private javax.swing.JCheckBox txtlihat;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
