/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import bukawarung.koneksiDB;
import java.awt.Color;
import java.awt.event.InputMethodEvent;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author USER
 */
public class menu_utama extends javax.swing.JFrame {
    koneksiDB getcnn = new koneksiDB();
    public String user = "";
Connection _cnn;
    private static String lev_user = "";
    private static String id_user= "";
   
    ResultSet data1=null;
    
    public menu_utama(String lev_user) {
        initComponents();
        disable_menu();
        this.id_user = lev_user;
        id_user = "nama_user";
        
        this.lev_user = lev_user;
        if(!lev_user.equals("Kasir")){
            btntm.setBackground(Color.GRAY);
            btn_transaksi.setBackground(Color.GRAY);
            
        }
        this.lev_user = lev_user;
        if(!lev_user.equals("Pemilik Toko")){
            btntp.setForeground(Color.GRAY);
            btnd_suplier.setBackground(Color.GRAY);
            btnedu.setForeground(Color.GRAY);
        }
        this.lev_user = lev_user;
        if(!lev_user.equals("Petugas Gudang")){
            btnodb.setBackground(Color.GRAY);
            btn_retur.setBackground(Color.GRAY);
        
    }
        
        
    }
   
        
     private void disable_menu(){
        pnlnav.setVisible(false);
    }
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlnav = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        btnedu = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        btntp = new javax.swing.JLabel();
        pnlmenu = new javax.swing.JPanel();
        pnltmb_pegawai = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btntm = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnodb = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_transaksi = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnd_suplier = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btn_retur = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblnav = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Utama");
        setUndecorated(true);

        pnlnav.setBackground(new java.awt.Color(0, 138, 0));
        pnlnav.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                pnlnavCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Log out");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });

        btnedu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnedu.setForeground(new java.awt.Color(255, 255, 255));
        btnedu.setText("Edit data User");
        btnedu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneduMouseClicked(evt);
            }
        });

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-admin-settings-male-32.png"))); // NOI18N

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-exit-32.png"))); // NOI18N

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-shop-96.png"))); // NOI18N

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-add-user-male-32.png"))); // NOI18N

        btntp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btntp.setForeground(new java.awt.Color(255, 255, 255));
        btntp.setText("Tambah Pegawai");
        btntp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlnavLayout = new javax.swing.GroupLayout(pnlnav);
        pnlnav.setLayout(pnlnavLayout);
        pnlnavLayout.setHorizontalGroup(
            pnlnavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnavLayout.createSequentialGroup()
                .addGroup(pnlnavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlnavLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btntp))
                    .addGroup(pnlnavLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlnavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlnavLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnedu))
                            .addGroup(pnlnavLayout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27)))
                        .addGap(37, 37, 37))
                    .addGroup(pnlnavLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel32)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlnavLayout.setVerticalGroup(
            pnlnavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnavLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel32)
                .addGap(60, 60, 60)
                .addGroup(pnlnavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btntp)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlnavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnedu)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(pnlnavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel27))
                .addContainerGap(274, Short.MAX_VALUE))
        );

        pnlmenu.setPreferredSize(new java.awt.Dimension(700, 540));
        pnlmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlmenuMouseClicked(evt);
            }
        });
        pnlmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnltmb_pegawai.setBackground(new java.awt.Color(255, 255, 255));
        pnltmb_pegawai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnltmb_pegawai.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-add-user-male-64.png"))); // NOI18N
        pnltmb_pegawai.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 138, 0));
        jLabel4.setText("Tambah Member");
        pnltmb_pegawai.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        btntm.setBackground(new java.awt.Color(0, 138, 0));
        btntm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btntmMouseEntered(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tambah");

        javax.swing.GroupLayout btntmLayout = new javax.swing.GroupLayout(btntm);
        btntm.setLayout(btntmLayout);
        btntmLayout.setHorizontalGroup(
            btntmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btntmLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(31, 31, 31))
        );
        btntmLayout.setVerticalGroup(
            btntmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnltmb_pegawai.add(btntm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 110, 30));

        pnlmenu.add(pnltmb_pegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 185, 185));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-package-64.png"))); // NOI18N
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 138, 0));
        jLabel7.setText("Olah Data Barang");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        btnodb.setBackground(new java.awt.Color(0, 138, 0));
        btnodb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnodbMouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Masuk");

        javax.swing.GroupLayout btnodbLayout = new javax.swing.GroupLayout(btnodb);
        btnodb.setLayout(btnodbLayout);
        btnodbLayout.setHorizontalGroup(
            btnodbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnodbLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(31, 31, 31))
        );
        btnodbLayout.setVerticalGroup(
            btnodbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel7.add(btnodb, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 30));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-package-64.png"))); // NOI18N
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 138, 0));
        jLabel10.setText("Olah Data Barang");
        jPanel10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jPanel12.setBackground(new java.awt.Color(0, 138, 0));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Masuk");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(31, 31, 31))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 30));

        jPanel7.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 185, 185));

        pnlmenu.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 185, 185));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-transaction-64.png"))); // NOI18N
        jPanel13.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 138, 0));
        jLabel13.setText("Transaksi");
        jPanel13.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        btn_transaksi.setBackground(new java.awt.Color(0, 138, 0));
        btn_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_transaksiMouseClicked(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tambah");

        javax.swing.GroupLayout btn_transaksiLayout = new javax.swing.GroupLayout(btn_transaksi);
        btn_transaksi.setLayout(btn_transaksiLayout);
        btn_transaksiLayout.setHorizontalGroup(
            btn_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_transaksiLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(31, 31, 31))
        );
        btn_transaksiLayout.setVerticalGroup(
            btn_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel13.add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 30));

        pnlmenu.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 185, 185));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-shipped-64 (3).png"))); // NOI18N
        jPanel16.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 138, 0));
        jLabel16.setText("Data Suplier");
        jPanel16.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        btnd_suplier.setBackground(new java.awt.Color(0, 138, 0));
        btnd_suplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnd_suplierMouseClicked(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Tambah");

        javax.swing.GroupLayout btnd_suplierLayout = new javax.swing.GroupLayout(btnd_suplier);
        btnd_suplier.setLayout(btnd_suplierLayout);
        btnd_suplierLayout.setHorizontalGroup(
            btnd_suplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnd_suplierLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(31, 31, 31))
        );
        btnd_suplierLayout.setVerticalGroup(
            btnd_suplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel16.add(btnd_suplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 30));

        pnlmenu.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 185, 185));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-return-purchase-64.png"))); // NOI18N
        jPanel19.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 138, 0));
        jLabel19.setText("Retur Barang");
        jPanel19.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        btn_retur.setBackground(new java.awt.Color(0, 138, 0));
        btn_retur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_returMouseClicked(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Tambah");

        javax.swing.GroupLayout btn_returLayout = new javax.swing.GroupLayout(btn_retur);
        btn_retur.setLayout(btn_returLayout);
        btn_returLayout.setHorizontalGroup(
            btn_returLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_returLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(31, 31, 31))
        );
        btn_returLayout.setVerticalGroup(
            btn_returLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel19.add(btn_retur, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 30));

        pnlmenu.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 185, 185));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 138, 0));
        jLabel2.setText("BukaWarung");

        lblnav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-menu-32.png"))); // NOI18N
        lblnav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblnavMouseClicked(evt);
            }
        });

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-delete-32.png"))); // NOI18N
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-subtract-32.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblnav)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel33)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnav)
                    .addComponent(jLabel2))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlnav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(pnlmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addComponent(pnlnav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(890, 610));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_transaksiMouseClicked(MouseEvent evt) {//GEN-FIRST:event_btn_transaksiMouseClicked
         if(lev_user.equals("Kasir")){
            btn_transaksi.setEnabled(true);
            new penjualan().setVisible(true);
            this.dispose();
            }else{
                btn_transaksi.setEnabled(false);
            }
    }//GEN-LAST:event_btn_transaksiMouseClicked

    private void btnodbMouseClicked(MouseEvent evt) {//GEN-FIRST:event_btnodbMouseClicked
         if(lev_user.equals("Petugas Gudang")){
            btnodb.setEnabled(true);
            this.dispose();
            new olahdata_barang().setVisible(true);
            }else{
                btnodb.setEnabled(false);
            }
    }//GEN-LAST:event_btnodbMouseClicked

    private void btntmMouseClicked(MouseEvent evt) {//GEN-FIRST:event_btntmMouseClicked
            if(lev_user.equals("Kasir")){
            btntm.setEnabled(true);
            new tambah_member().setVisible(true);
            this.dispose();
            }else{
                btntm.setEnabled(false);
            }
    }//GEN-LAST:event_btntmMouseClicked

    private void jLabel27MouseClicked(MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel27MouseClicked

    private void btneduMouseClicked(MouseEvent evt) {//GEN-FIRST:event_btneduMouseClicked
       if(lev_user.equals("Pemilik Toko")){
            btnedu.setEnabled(true);
            new editdata().setVisible(true);
            this.dispose();
            }else{
                btnedu.setEnabled(false);
            }
    }//GEN-LAST:event_btneduMouseClicked

    private void btn_returMouseClicked(MouseEvent evt) {//GEN-FIRST:event_btn_returMouseClicked
         if(lev_user.equals("Petugas Gudang")){
            btn_retur.setEnabled(true);
            new retur().setVisible(true);
            this.dispose();
            }else{
                btn_retur.setEnabled(false);
            }
    }//GEN-LAST:event_btn_returMouseClicked

    private void btntpMouseClicked(MouseEvent evt) {//GEN-FIRST:event_btntpMouseClicked
       if(lev_user.equals("Pemilik Toko")){
            btntp.setEnabled(true);
            new tambah_pegawai().setVisible(true);
            this.dispose();
            }else{
                btntp.setEnabled(false);
            }
                                     
    }//GEN-LAST:event_btntpMouseClicked

    private void btntmMouseEntered(MouseEvent evt) {//GEN-FIRST:event_btntmMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btntmMouseEntered

    private void btnd_suplierMouseClicked(MouseEvent evt) {//GEN-FIRST:event_btnd_suplierMouseClicked
         if(lev_user.equals("Pemilik Toko")){
            btnd_suplier.setEnabled(true);
            new data_suplier().setVisible(true);
            this.dispose();
            }else{
                btnd_suplier.setEnabled(false);
            }
    }//GEN-LAST:event_btnd_suplierMouseClicked

    private void lblnavMouseClicked(MouseEvent evt) {//GEN-FIRST:event_lblnavMouseClicked
     pnlnav.setVisible(true);
     lblnav.setVisible(false);
      
     
    }//GEN-LAST:event_lblnavMouseClicked

    private void pnlmenuMouseClicked(MouseEvent evt) {//GEN-FIRST:event_pnlmenuMouseClicked
     pnlnav.setVisible(false);   
     lblnav.setVisible(true);
    }//GEN-LAST:event_pnlmenuMouseClicked

    private void pnlnavCaretPositionChanged(InputMethodEvent evt) {//GEN-FIRST:event_pnlnavCaretPositionChanged
       
    }//GEN-LAST:event_pnlnavCaretPositionChanged

    private void jLabel33MouseClicked(MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        new Login().show();
        this.dispose();
    }//GEN-LAST:event_jLabel33MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_utama(lev_user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_retur;
    private javax.swing.JPanel btn_transaksi;
    private javax.swing.JPanel btnd_suplier;
    private javax.swing.JLabel btnedu;
    private javax.swing.JPanel btnodb;
    private javax.swing.JPanel btntm;
    private javax.swing.JLabel btntp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblnav;
    private javax.swing.JPanel pnlmenu;
    private javax.swing.JPanel pnlnav;
    private javax.swing.JPanel pnltmb_pegawai;
    // End of variables declaration//GEN-END:variables
}
